---
title: "NBABusiness"
output: html_document
Name: Malik Khan
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(plyr)
```

```{r}
GameData = read.csv("/Users/malikkhan/Desktop/game_data.csv")
PlayerData = read.csv("/Users/malikkhan/Desktop/player_data.csv")
TrainingSet = read.csv("/Users/malikkhan/Desktop/training_set.csv")

CleanedSet <- data.frame(matrix(nrow = 2460, ncol = 8), stringsAsFactors = FALSE)
CleanedNames <- c("game_id", "team_1", "team_2","win_1", "win_2", "total_active_stars", "cum_final_score", "total_views")
colnames(CleanedSet) <- as.factor(CleanedNames)
CleanedSet[1:2460,1] <- c(unique(GameData[,"Game_ID"])) #2460 unique game ids 

for (i in 1:nrow(CleanedSet)){
  elems = which(GameData$Game_ID == CleanedSet[i,"game_id"]) 
  
  CleanedSet[i, "team_1"] = as.character(GameData$Team[elems[1]])
  
  CleanedSet[i, "team_2"] = as.character(GameData$Team[elems[2]])
  
  WhichAS1 = which(PlayerData$Game_ID == CleanedSet[i,"game_id"] & PlayerData$Team == CleanedSet[i,"team_1"])
  WhichAS2 = which(PlayerData$Game_ID == CleanedSet[i,"game_id"] & PlayerData$Team == CleanedSet[i,"team_2"])
  AS1 = sum(PlayerData$ASG_Team[WhichAS1] != "None")
  AS2 = sum(PlayerData$ASG_Team[WhichAS2] != "None")
  
  InactiveAS1 = length(which(PlayerData$ASG_Team[WhichAS1] != "None" & PlayerData[WhichAS1,"Active_Status"] == "Inactive"))
  InactiveAS2 = length(which(PlayerData$ASG_Team[WhichAS2] != "None" & PlayerData[WhichAS2,"Active_Status"] == "Inactive"))
  
  CleanedSet[i, "total_active_stars"] = (AS1-InactiveAS1) + (AS2-InactiveAS2)

  CleanedSet[i, "win_1"] = round((GameData$Wins_Entering_Gm[elems[1]] / (GameData$Wins_Entering_Gm[elems[1]] + GameData$Losses_Entering_Gm[elems[1]]))*100, 2)
  
  CleanedSet[i, "win_2"] = round((GameData$Wins_Entering_Gm[elems[2]] / (GameData$Wins_Entering_Gm[elems[2]] + GameData$Losses_Entering_Gm[elems[2]]))*100, 2)
  
  if (is.nan(CleanedSet[i, "win_1"])){
    CleanedSet[i, "win_1"] = 0
  }
  if (is.nan(CleanedSet[i, "win_2"])){
    CleanedSet[i, "win_2"] = 0
  }
  
  CleanedSet[i, "cum_final_score"] = GameData$Final_Score[elems[1]]+GameData$Final_Score[elems[2]] #cum score

  views = which(TrainingSet$Game_ID == CleanedSet[i, "game_id"]) #selected elems
  total = sum(TrainingSet[views,"Rounded.Viewers"])
  CleanedSet[i, "total_views"] = total
}

omitted = which(is.na(CleanedSet[,"cum_final_score"]))
CleanedSet = CleanedSet[-omitted,]

write.csv(CleanedSet, file = "cleaned_business_set.csv")
```
