---
title: "NBATestSET"
output: html_document
Name: Malik Khan
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#win1,win2, total active all stars,
GameData = read.csv("/Users/malikkhan/Desktop/game_data.csv")
PlayerData = read.csv("/Users/malikkhan/Desktop/player_data.csv")
TrainingSet = read.csv("/Users/malikkhan/Desktop/training_set.csv")
TestedSet = read.csv("/Users/malikkhan/Desktop/test_set.csv")
RevFaceTwit = read.csv("/Users/malikkhan/Desktop/NBAREVENUE.csv")

RevFaceTwit$Team = as.character(RevFaceTwit$Team)

CleanedTestSet <- data.frame(matrix(nrow = 460, ncol = 10), stringsAsFactors = FALSE)
CleanedTestNames <- c("game_id","team_1", "team_2","win_1", "win_2", "total_active_stars", "CombinedRevenues", "FBRatio", "TwitterRatio", "CombinedPPG")
colnames(CleanedTestSet) <- as.factor(CleanedTestNames)
CleanedTestSet[1:460,1] <- c(TestedSet[,"Game_ID"]) #460 unique game ids
for (i in 1:nrow(CleanedTestSet)){
  elems = which(GameData$Game_ID == CleanedTestSet[i,"game_id"]) 
  
  
  CleanedTestSet[i, "team_1"] = as.character(GameData$Team[elems[1]])
  
  CleanedTestSet[i, "team_2"] = as.character(GameData$Team[elems[2]])
  
  CleanedTestSet[i, "win_1"] = round((GameData$Wins_Entering_Gm[elems[1]] / (GameData$Wins_Entering_Gm[elems[1]] + GameData$Losses_Entering_Gm[elems[1]]))*100, 2)
  
  CleanedTestSet[i, "win_2"] = round((GameData$Wins_Entering_Gm[elems[2]] / (GameData$Wins_Entering_Gm[elems[2]] + GameData$Losses_Entering_Gm[elems[2]]))*100, 2)
  
  WhichAS1 = which(PlayerData$Game_ID == CleanedTestSet[i,"game_id"] & PlayerData$Team == CleanedTestSet[i,"team_1"])
  WhichAS2 = which(PlayerData$Game_ID == CleanedTestSet[i,"game_id"] & PlayerData$Team == CleanedTestSet[i,"team_2"])
  
  AS1 = sum(PlayerData$ASG_Team[WhichAS1] != "None")
  AS2 = sum(PlayerData$ASG_Team[WhichAS2] != "None")
  
  InactiveAS1 = length(which(PlayerData$ASG_Team[WhichAS1] != "None" & PlayerData[WhichAS1,"Active_Status"] == "Inactive"))
  InactiveAS2 = length(which(PlayerData$ASG_Team[WhichAS2] != "None" & PlayerData[WhichAS2,"Active_Status"] == "Inactive"))
  
  CleanedTestSet[i, "total_active_stars"] = (AS1-InactiveAS1) + (AS2-InactiveAS2)
  
  CleanedTestSet[i, "CombinedRevenues"] = RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_1"]), "Revenue"] + RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_2"]), "Revenue"]
  
  CleanedTestSet[i, "CombinedPPG"] = RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_1"]), "PPG"] + RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_2"]), "PPG"]
  
  FBFans = RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_1"]), "FB"] + RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_2"]), "FB"]
  
  FBRatio = FBFans/(RevFaceTwit[31, "FB"])
  
  CleanedTestSet[i, "FBRatio"] = FBRatio 
  
  TwitterFans = RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_1"]), "Twitter"] + RevFaceTwit[which(RevFaceTwit[,"Team"] == CleanedTestSet[i, "team_2"]), "Twitter"]
  
  TwitterRatio = TwitterFans/(RevFaceTwit[31, "Twitter"])
  
  CleanedTestSet[i, "TwitterRatio"] = TwitterRatio 
  
  if (is.nan(CleanedTestSet[i, "win_1"])){
    CleanedTestSet[i, "win_1"] = 0
  }
  if (is.nan(CleanedTestSet[i, "win_2"])){
    CleanedTestSet[i, "win_2"] = 0
  }
}
write.csv(CleanedTestSet, file = "cleaned_business_test_set.csv")


```

